language: node_js
node_js:
  - "12"
install:
  - npm install
cache:
  - npm

script:
  - npm run build
deploy:
  provider: pages # Deploy edd0818/nofap_chrome_ext to github.com/edd0818/nofap_chrome_ext.git:gh-pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
