language: node_js
node_js:
  - "12"
install:
  - npm install
cache:
  - npm

script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  repo: edd0818/edd0818.github.io/no-fap-ext
  target_branch: master
  on:
    branch: master
